name: Auto Release on Version Change

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  auto-release:
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract version from plugin file
      id: extract_version
      run: |
        VERSION=$(awk '/\* Version:/ {print $3}' webp-image-converter.php)
        echo "current_version=$VERSION" >> $GITHUB_OUTPUT
        echo "Current version detected: $VERSION"
    
    - name: Check if version tag exists
      id: check_tag
      run: |
        VERSION=${{ steps.extract_version.outputs.current_version }}
        if git rev-parse "v$VERSION" >/dev/null 2>&1; then
          echo "tag_exists=true" >> $GITHUB_OUTPUT
          echo "Tag v$VERSION already exists"
        else
          echo "tag_exists=false" >> $GITHUB_OUTPUT
          echo "Tag v$VERSION does not exist - will create release"
        fi
    
    - name: Extract changelog for current version
      id: changelog
      if: steps.check_tag.outputs.tag_exists == 'false'
      run: |
        VERSION=${{ steps.extract_version.outputs.current_version }}
        # Extract changelog section for current version from readme.txt
        CHANGELOG=$(awk "/^= $VERSION =/{flag=1; next} /^= [0-9]+\.[0-9]+\.[0-9]+ =/{if(flag) exit} flag" readme.txt | sed '/^$/d')
        if [ -z "$CHANGELOG" ]; then
          CHANGELOG="Version $VERSION release - see commit history for details."
        fi
        # Save changelog to file to preserve formatting
        echo "$CHANGELOG" > changelog.txt
        echo "Extracted changelog for version $VERSION"
    
    - name: Create Git tag
      if: steps.check_tag.outputs.tag_exists == 'false'
      run: |
        VERSION=${{ steps.extract_version.outputs.current_version }}
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a "v$VERSION" -m "Release version $VERSION"
        git push origin "v$VERSION"
        echo "Created and pushed tag v$VERSION"
    
    - name: Create plugin ZIP for distribution
      if: steps.check_tag.outputs.tag_exists == 'false'
      run: |
        # Create a clean copy of the plugin for distribution
        mkdir -p dist
        rsync -av --exclude='.git*' --exclude='dist' --exclude='*.md' --exclude='.github' . dist/webp-image-converter/
        
        # Create ZIP file
        cd dist
        zip -r "../webp-image-converter-${{ steps.extract_version.outputs.current_version }}.zip" webp-image-converter/
        cd ..
        
        echo "Created distribution ZIP file"
        ls -la webp-image-converter-*.zip
    
    - name: Create GitHub Release
      if: steps.check_tag.outputs.tag_exists == 'false'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.extract_version.outputs.current_version }}
        name: WebP Image Converter v${{ steps.extract_version.outputs.current_version }}
        body_path: changelog.txt
        files: |
          webp-image-converter-${{ steps.extract_version.outputs.current_version }}.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Log release completion
      if: steps.check_tag.outputs.tag_exists == 'false'
      run: |
        echo "✅ Successfully created release v${{ steps.extract_version.outputs.current_version }}"
        echo "📦 Distribution ZIP: webp-image-converter-${{ steps.extract_version.outputs.current_version }}.zip"
        echo "🚀 WordPress sites with auto-updater will detect this release within 1 minute"
    
    - name: Skip release creation
      if: steps.check_tag.outputs.tag_exists == 'true'
      run: |
        echo "⏭️  Skipped release creation - tag v${{ steps.extract_version.outputs.current_version }} already exists"